from tkinter import *
root = Tk()
root.title("Login")
root.geometry("300x250")
LoginFormLabel = Label(root, text="Login Form", font=("Arial", 25, "bold"), justify=CENTER)
LoginFormLabel.grid(row=0, column=0, columnspan=2, padx=10, pady=10)
UsernameLabel = Label(root, text="Username:", font=("Arial", 12))
UsernameLabel.grid(row=1, column=0, padx=10, pady=10)
username = Entry(root, font=("Arial", 12), justify=CENTER)
username.grid(row=1, column=1, padx=10, pady=10)
PasswordLabel = Label(root, text="Password:", font=("Arial", 12))
PasswordLabel.grid(row=2, column=0, padx=10, pady=10)
password = Entry(root, font=("Arial", 12), justify=CENTER)
password.grid(row=2, column=1, padx=10, pady=10)
login_button = Button(root, text="Submit", font=("Arial", 12, "bold"))
login_button.grid(row=3, column=0, columnspan=2, padx=10, pady=10)
root.mainloop()